name: "My first workflow"
on: "push"
jobs:
  first-job:
    runs-on: "ubuntu-latest"
    steps:
      - name: "print to console"
        run: "echo hey!"
  run-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get code"
        run: actions/checkout@v3
      - name: "Install dependencies"
        run: npm ci
      - name: "Run tests"
        run: npm test
