name: "my first workflow"
on: ["workflow_dispatch", "push"]
jobs:
  first-job:
    runs-on: "ubuntu-latest"
    steps:
      - name: "print to console"
        run: 'echo "hey"'
  testing:
    needs: "first-job"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get repo"
        uses: actions/checkout@v3
      - name: "Install our dependencies"
        run: "npm i"
      - name: "test our code"
        run: "npm run test"
  output-report:
    needs: "testing"
    if: failure()
    runs-on: "ubuntu-latest"
    steps:
      - name: "write report"
        run: "echo here is your report"
