name: "My first workflow"
on:
  pull_request:
    types:
      - "opened"
  push:
    branches:
      - "main"
jobs:
  first-job:
    runs-on: "ubuntu-latest"
    steps:
      - name: "print to console"
        run: "echo hey!"
  run-test:
    runs-on: "ubuntu-latest"
    needs: "first-job"
    steps:
      - name: "Get code"
        uses: actions/checkout@v3
      - name: "Install dependencies"
        run: npm ci
      - name: "Run tests"
        run: npm test
